#
# The oob-mgmt-server acts as the Internet gateway to fabric
#
# Perform NAT for remote access to Horizon UI and the demo floating IP address
#

- set_fact:
    myvars: "{{ servervars[inventory_hostname] }}"

- name: Set up DNAT for Horizon UI
  blockinfile:
    dest: /etc/rc.local
    insertbefore: "exit 0"
    marker: "# {mark} ANSIBLE MANAGED BLOCK UI DNAT"
    block: |
      /sbin/iptables -t nat -A PREROUTING -p tcp --dport {{ HORIZON_UI }} --in-interface eth0 -j DNAT --to-destination {{ servervars[ HORIZON_HOST ].V4 }}:{{ HORIZON_UI }}
  become: true
  register: _horizon_dnat
- iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    destination_port: "{{ HORIZON_UI }}"
    jump: DNAT
    to_destination: "{{ servervars[ HORIZON_HOST ].V4 }}:{{ HORIZON_UI }}"
  become: yes
  when: _horizon_dnat | changed

# Perhaps someday if we get the shutdown/startup figured out :-)
#
# - name: Set up DNAT for ssh access to cirros1 via the floating IP
#   shell: ssh {{ HORIZON_HOST }} "openstack {{ openstack.demo_credentials }} floating ip list -c 'Floating IP Address' -f value"
#   register: _floating_ip
# - blockinfile:
#     dest: /etc/rc.local
#     insertbefore: "exit 0"
#     marker: "# {mark} ANSIBLE MANAGED BLOCK CIRROS1 SSH DNAT"
#     block: |
#       /sbin/iptables -t nat -A PREROUTING -p tcp --dport {{ FLOATING_SSH }} --in-interface eth0 -j DNAT --to-destination {{ _floating_ip.stdout }}:22
#   become: yes
#   register: _ssh_dnat
# - iptables:
#     table: nat
#     chain: PREROUTING
#     in_interface: eth0
#     protocol: tcp
#     destination_port: "{{ FLOATING_SSH }}"
#     jump: DNAT
#     to_destination: "{{ _floating_ip.stdout }}:22"
#   become: yes
#   when: _ssh_dnat | changed

